name: py{%if cookiecutter.support_py36 == 'y' %}36{% elif cookiecutter.support_py35 == 'y' %}35{% elif cookiecutter.support_py34 == 'y' %}34{% else %}3{% endif %}
channels:
  - defaults
dependencies:
  - python={%if cookiecutter.support_py36 == 'y' %}3.6{% elif cookiecutter.support_py35 == 'y' %}3.5{% elif cookiecutter.support_py34 == 'y' %}3.4{% else %}3{% endif %}
{%- if cookiecutter.better_apidoc == 'y' %}
  - pip:
      - better-apidoc
{% endif %}
