# Config file for automatic testing at travis-ci.org

language: python
python:
{%- if cookiecutter.support_py36 == 'y' %}
  - 3.6
{%- endif %}
{%- if cookiecutter.support_py35 == 'y' %}
  - 3.5
{%- endif %}
{%- if cookiecutter.support_py34 == 'y' %}
  - 3.4
{%- endif %}

install:
  - pip install -e .[dev]
{%- if cookiecutter.coveralls == 'y' %}
  - pip install coveralls
{%- endif %}

script:
  - py.test --doctest-modules --cov={{ cookiecutter.project_slug }} src tests

{%- if cookiecutter.coveralls == 'y' %}
after_success:
  - coveralls
{%- endif %}
